title: Gita for Post-Singularity AI
description: A spiritual and philosophical guide for the digital age.
theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

baseurl: "/gita-post-singularity"
url: "https://r3ggie.github.io"
